### ISSUE TITLE
Needs updating to latest ytdl version

### ISSUE THREAD

**Issue by benkaiser** [ytdl-js/react-native-ytdl#61]
I tried running the auto-patcher but it seemed to fail on a bunch of the files:

```
Processing 14 files...
Spawning 7 workers...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
Sending 2 files to free worker...
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\sig.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\index.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\index.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\__REACT_NATIVE_YTDL_CUSTOM_MODULES__\m3u8stream\index.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\cache.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\format-utils.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\url-utils.js"
use_custom_module_implementations_transform.js: redirecting module "miniget" to "./__REACT_NATIVE_YTDL_CUSTOM_MODULES__/miniget"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\__REACT_NATIVE_YTDL_CUSTOM_MODULES__\sax\index.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\__REACT_NATIVE_YTDL_CUSTOM_MODULES__\miniget\index.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\info-extras.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\info.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\__REACT_NATIVE_YTDL_CUSTOM_MODULES__\sax\sax.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\utils.js"
use_custom_module_implementations_transform.js: processing "__AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\formats.js"
use_custom_module_implementations_transform.js: redirecting module "m3u8stream" to "./__REACT_NATIVE_YTDL_CUSTOM_MODULES__/m3u8stream"
use_custom_module_implementations_transform.js: redirecting module "sax" to "./__REACT_NATIVE_YTDL_CUSTOM_MODULES__/sax"
use_custom_module_implementations_transform.js: redirecting module "miniget" to "./__REACT_NATIVE_YTDL_CUSTOM_MODULES__/miniget"
 ERR __AUTO_PATCHER__\tmp\__AUTO_PATCHER_OUTPUT__\lib\utils.js Transformation error (Unexpected reserved word 'package' (143:6))
SyntaxError: Unexpected reserved word 'package' (143:6)
    at Object._raise (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\error.js:60:45)
    at Object.raiseWithData (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\error.js:55:17)
    at Object.raise (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\error.js:39:17)
    at Object.checkReservedWord (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\expression.js:2336:14)
    at Object.parseIdentifierName (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\expression.js:2277:12)
    at Object.parseIdentifier (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\expression.js:2235:23)
    at Object.parseBindingAtom (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\lval.js:299:17)
    at Object.parseVarId (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\statement.js:1044:20)
    at Object.parseVar (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\statement.js:1006:12)
    at Object.parseVarStatement (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\statement.js:700:10)
All done.
Results:
1 errors
10 unmodified
0 skipped
3 ok
Time elapsed: 3.997seconds
Processing 1 files...
Spawning 1 workers...
Sending 1 files to free worker...
change_update_warning_transform.js: processing "__AUTO_PATCHER__/tmp/__AUTO_PATCHER_OUTPUT__/lib/utils.js"
 ERR __AUTO_PATCHER__/tmp/__AUTO_PATCHER_OUTPUT__/lib/utils.js Transformation error (Unexpected reserved word 'package' (143:6))
SyntaxError: Unexpected reserved word 'package' (143:6)
    at Object._raise (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\error.js:60:45)
    at Object.raiseWithData (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\error.js:55:17)
    at Object.raise (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\error.js:39:17)
    at Object.checkReservedWord (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\expression.js:2336:14)
    at Object.parseIdentifierName (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\expression.js:2277:12)
    at Object.parseIdentifier (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\expression.js:2235:23)
    at Object.parseBindingAtom (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\lval.js:299:17)
    at Object.parseVarId (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\statement.js:1044:20)
    at Object.parseVar (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\statement.js:1006:12)
    at Object.parseVarStatement (C:\Users\bekaise\AppData\Roaming\nvm\v10.22.1\node_modules\jscodeshift\node_modules\@babel\parser\src\parser\statement.js:700:10)
All done.
Results:
1 errors
0 unmodified
0 skipped
0 ok
Time elapsed: 1.675seconds
```

**Comment by AbelTesfaye** [comment]
It was failing because of new changes that introduced an invalid variable name. I opened an [issue](https://github.com/fent/node-ytdl-core/issues/834) on node-ytdl-core.

The latest release is published with a temporary fix
